import watermark from "../assets/img/watermark.png"
import A0 from "../assets/img/A0.png"
import C0 from "../assets/img/C0.png"
import C1 from "../assets/img/C1.png"
import C2 from "../assets/img/C2.png"
import C3 from "../assets/img/C3.png"
import C4 from "../assets/img/C4.png"
import C5 from "../assets/img/C5.png"
import C6 from "../assets/img/C6.png"
import C7 from "../assets/img/C7.png"
import C8 from "../assets/img/C8.png"
import C9 from "../assets/img/C9.png"
import C10 from "../assets/img/C10.png"
import C11 from "../assets/img/C11.png"
import C12 from "../assets/img/C12.png"
import F0 from "../assets/img/F0.png"
import F1 from "../assets/img/F1.png"
import F2 from "../assets/img/F2.png"
import F3 from "../assets/img/F3.png"
import F4 from "../assets/img/F4.png"
import F5 from "../assets/img/F5.png"
import F6 from "../assets/img/F6.png"
import F7 from "../assets/img/F7.png"
import F8 from "../assets/img/F8.png"
import F9 from "../assets/img/F9.png"
import F10 from "../assets/img/F10.png"
import F11 from "../assets/img/F11.png"
import H0 from "../assets/img/H0.png"
import H1 from "../assets/img/H1.png"
import H2 from "../assets/img/H2.png"
import H3 from "../assets/img/H3.png"
import H4 from "../assets/img/H4.png"
import H5 from "../assets/img/H5.png"
import H6 from "../assets/img/H6.png"
import H7 from "../assets/img/H7.png"
import H8 from "../assets/img/H8.png"
import H9 from "../assets/img/H9.png"
import H10 from "../assets/img/H10.png"
import H11 from "../assets/img/H11.png"
import H12 from "../assets/img/H12.png"
import H13 from "../assets/img/H13.png"
import H14 from "../assets/img/H14.png"

export const img ={
    watermark, A0, 
    C0, C1, C2, C3, C4, C5, C6, C7, C8, C9, C10, C11, C12, 
    F0, F1, F2, F3, F4, F5, F6, F7, F8, F9, F10, F11, 
    H0, H1, H2, H3, H4, H5, H6, H7, H8, H9, H10, H11, H12, H13, H14
}